import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
 
load_dotenv()
 
EMAIL_SENDER   = os.getenv("EMAIL_SENDER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_RECEIVER = os.getenv("EMAIL_RECEIVER")
 
 
def send_failure_email(job_name, build_number, explanation):
    print("Preparing email...")
 
    subject = f"Jenkins Build Failed - {job_name} #{build_number}"
 
    body = f"""
Jenkins Pipeline Failure Report
================================
 
{explanation}
 
================================
This email was auto-generated by your Jenkins AI Explainer.
"""
 
    msg = MIMEMultipart()
    msg["From"]    = EMAIL_SENDER
    msg["To"]      = EMAIL_RECEIVER
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))
 
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())
        print(f"Email sent successfully to {EMAIL_RECEIVER}")
        return True
    except smtplib.SMTPAuthenticationError:
        print("Email failed: wrong Gmail credentials. Use an App Password, not your real password.")
        return False
    except Exception as e:
        print(f"Email failed: {e}")
        return False
 
